//
//  Const.swift
//  ResourceKit
//
//  Created by Yudai.Hirose on 2017/09/24.
//  Copyright © 2017年 kingkong999yhirose. All rights reserved.
//

import Foundation

let newLine = "\n"
let tab1 = "\t"
let tab2 = "\t\t"
let tab3 = "\t\t\t"

let Header = [
    "// This is a generated file \n",
    "// Generated by ResouceKit \n",
    "// You can write custom imoprt XXXX logic"
].joined(separator: "") + newLine

