# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SegueAddition'

target 'ResourceKitDemo' do

end

target 'ResourceKitDemoTests' do

end

target 'ResourceKitDemoUITests' do

end

