//
//  Const.swift
//  ResourceKit
//
//  Created by Yudai.Hirose on 2017/09/24.
//  Copyright © 2017年 kingkong999yhirose. All rights reserved.
//

import Foundation

public struct Const {
    public static let newLine = "\n"
    public static let tab1 = "\t"
    public static let tab2 = "\t\t"
    public static let tab3 = "\t\t\t"

    public static let Header = [
        "// This is a generated file \n",
        "// Generated by ResouceKit \n",
        "// You can write custom imoprt XXXX logic"
        ].joined(separator: "") + Const.newLine

}

